### ISSUE TITLE
-Jred -JAASteensgaardRegionAware segfaults

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#194] opened 2023-02-05 11:26 UTC
jlc -Jred -JAASteensgaardRegionAware red.c
[red.zip](https://github.com/phate/jlm/files/10610811/red.zip)

**Comment by sjalander** [comment] 2023-11-03 08:50
Problem resolved

**Comment by phate** [comment] 2024-04-09 04:23
Closing this issue as I cannot reproduce it any longer.

**Closed by phate** 2024-04-09 04:23 UTC
