### ISSUE TITLE
C-code causing jlc to generate an executable that never terminates

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#9] opened 2020-09-28 09:48 UTC
Commands for replicating the error
jlc -I$(CSMITH_HOME)/runtime -O test-no-termination.c -o test.jlc;
./test.jlc

[no-termiantion.zip](https://github.com/phate/jlm/files/5292805/no-termiantion.zip)

**Comment by phate** [comment] 2020-10-04 20:09
What exactly is the problem with this C file? Compiled with jlc, the resulting program seems to be non-terminating, but so is it when compiled with gcc or clang.

**Comment by sjalander** [comment] 2020-10-04 20:32
clang-7 generated executable produces the following output
checksum = 846A8480
while jlc generated executable never completes.

**Comment by phate** [comment] 2020-10-04 21:11
Closing it, as I sadly cannot reproduce the problem...

**Closed** 2020-10-04 21:12 UTC
