### ISSUE TITLE
-JAASteensgaardAgnostic causes resulting binary to produce incorrect output

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#320] opened 2023-12-12 09:11 UTC
**Recreate**
_make_

**Reference**: 0.949734
**Output**: 0.000000

[dt.zip](https://github.com/phate/jlm/files/13646047/dt.zip)

**Comment by phate** [comment] 2024-04-11 05:25
I am closing this issue as I cannot reproduce this problem any longer. Executing the program gives me the reference output. Moreover, the program is from the LLVM test suite, and I just checked the test there and it gives me the correct result for the SteensgaardAgnostic run. The program is also enabled as part of the SteensgaardAgnostic CI run and we would realize if it would break (again).

**Closed by phate** 2024-04-11 05:25 UTC
Labels: bug
